"""chats table

Revision ID: 9365bcfad837
Revises: 3ba7f969c02f
Create Date: 2024-08-04 19:08:59.415328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9365bcfad837'
down_revision = '3ba7f969c02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index('ix_chats_user_id')

    op.drop_table('chats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('msg', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('content', sa.VARCHAR(length=4096), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index('ix_chats_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_user_id'))

    op.drop_table('chat')
    # ### end Alembic commands ###
